export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';

export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';

export const EDIT_ACTIVITY = 'EDIT_ACTIVITY';

export const SAVE_EDITTED_ACTIVITY = 'SAVE_EDITTED_ACTIVITY';
