export const WEATHER_CODES: Record<number, string> = {
	0: 'Clear sky',
	1: 'Mainly clear',
	2: 'Partly cloudy',
	3: 'Overcast',
	45: 'Fog',
	48: 'Depositing rime fog',
	51: 'Light drizzle',
	53: 'Moderate drizzle',
	55: 'Dense intensity drizzle',
	56: 'Freezing drizzle: Light',
	57: 'Freezing drizzle: Dense intensity',
	61: 'Rain: Slight',
	63: 'Rain: Moderate',
	65: 'Rain: Heavy intensity',
	66: 'Freezing Rain: Light',
	67: 'Freezing Rain: Heavy intensity',
	71: 'Snow fall: Slight',
	73: 'Snow fall: Moderate',
	75: 'Snow fall: Heavy intensity',
	77: 'Snow grains',
	80: 'Rain showers: Slight',
	81: 'Rain showers: Moderate',
	82: 'Rain showers: Violent',
	85: 'Snow showers: slight ',
	86: 'Snow showers: heavy'
};
